export const translate = {
    ИУ: 'IU',
    АК: 'AK',
    РКТ: 'RKT',
    RТ: 'RT',
    ИСОТ: 'ISOT',
    ОЭ: 'OE',
    ПС: 'PS',
    ИБМ: 'IBM',
    МТ: 'MT',
    СМ: 'CM',
    БМТ: 'BMT',
    РЛ: 'RL',
    Э: 'E',
    РК: 'RK',
    ФН: 'FN',
    Л: 'L',
    ЮР: 'UR',
    СГН: 'SGN',
}